### PR TITLE
utils: fix for NaN comparison

### LINKED ISSUE #54: NaN comparison
right now NaNs compare as different, here's a patch to __init__.py to fix it:

-        if first != second:
+        if first != second and [first] != [second]:

### PR DESCRIPTION
**Pull request by jirikuncar**
* BETTER Adds support for comparing numerical values and NaN.
  (closes #54) (closes #55)

Co-authored-by: Jiri Kuncar <jiri.kuncar@cern.ch>

### CODE REVIEW

**Comment by jirikuncar** [comment]
@thehesiod can you please have a look if it solves your problem and the code is correct?

(cc @frodon1 as I'm changing his recent code)

**Comment by frodon1** [comment]
In the commit message: s/numberical/numerical

**Comment by jirikuncar** [comment]
@frodon1 thanks :+1:

**Comment by thehesiod** [comment]
as long as the unites passes :)

**Pull request merged**
