### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by adrien-berchet**
Fix the Numpy versions and use Anaconda to make the CI pass.

### CODE REVIEW

**Comment by adrien-berchet** [comment]
Hello
Here is an attempt to fix the CI so it is possible to merge #152 (I would really need it) and make a new release.

**Comment by adrien-berchet** [comment]
I prefer it as it is much simpler, I just didn't want to change the requirements but if it's ok for you it's ok for me :)

**Comment by joesolly** [comment]
> I prefer it as it is much simpler, I just didn't want to change the requirements but if it's ok for you it's ok for me :)

In my opinion, it's totally fine. It is only for an extra requirement install, it does not restrict someone from installing a different version of Numpy on their own.

**Comment by adrien-berchet** [comment]
I agree, let's take your version.

**Pull request closed without merging**
