### PR TITLE
diff: support for collections.Mapping comparison

### PR DESCRIPTION
**Pull request by jrjsmrtn**
* allow use of ldap3.utils.ciDict.CaseInsensitiveDict or other specialized dictionaries in diff()

### CODE REVIEW

**Comment by jirikuncar** [comment]
@jrjsmrtn do you have any {use,test}-case for this feature?

- [ ] Please follow the commit message style (`git commit --amend`, `git push orgin master --force`) - it's better if you use topical branches (GitHub guide: https://guides.github.com/introduction/flow/).
- [ ] Add tests to keep coverage.
- [ ] Update documentation (use `.. versionchanged:: 0.5.1` - http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionchanged).
- [ ] Please add yourself to `AUTHORS`.
- [ ] Please reply if you agree to donate this (and any future) contributions to *dictdiffer* package under the terms of the Revised BSD Licence.

**Comment by jrjsmrtn** [comment]
@jirikuncar: my main use case is to get differences on ldap3 CaseInsensistiveDicts.

Thus, is that ok if I add ldap3 to setup.py's tests_require and import it to perform additional tests ?

**Comment by jirikuncar** [comment]
@jrjsmrtn you should add test case where you `diff` some custom instances of `collections.Mapping`.

**Comment by skolsuper** [comment]
I am having a similar problem, I have a collection that is an immutable dictionary of lists of dictionaries of dictionaries and am implementing a custom container class to make life easier.  I tried this:
```python
class MyCustomClass(object):
    def __getitem__(self, item):
        return getattr(self, item)
```
so that I could continue to use dictdiffer, but it seems that won't work because of the type checking.  In my opinion, it would be more pythonic to do duck-typing `try: ... except` blocks than using `isinstance` or `issubclass`, if at all possible.

**Comment by jirikuncar** [comment]
@skolsuper can you inherit from `collections.MutableMapping`?

```python
class MyCustomClass(collections.MutableMapping):
    def __getitem__(self, item):
        return getattr(self, item)
```

Please make sure that you are *not* trying to `diff` immutable objects. There is no sense in generating patch from such object as it can't be applied.

**Comment by skolsuper** [comment]
Hi @jirikuncar, thanks for the rapid response!

To expand on my use case, I am retrieving quite complex objects I get from a 3rd party API that could change, and am using dictdiffer to record any changes in an object since I last checked.  Am I missing some easier way to achieve this?

If not, I will consider inheriting from MutableMapping as you suggest.  I still think it would be [more pythonic](https://docs.python.org/3/glossary.html#term-eafp) to lose the `isinstance` checks but its not a deal-breaker 😄

**Comment by jirikuncar** [comment]
@skolsuper if you know about better way how to guess if an object is mapping, list or set, we are happy to include it (if there is not major performance problem).

--
Please open separate issue to discuss possible solutions. Thanks!

**Comment by skolsuper** [comment]
I have decided to just serialize my objects back into dicts before I diff them.

**Pull request closed without merging**
